---
title: "tharunte_Homework_3"
output: pdf_document
---

# Question 1
Exhibit 1.1 Time Series Plot of Los Angeles Annual Rainfall
```{R}
library(TSA)
# win.graph(width=4.875, height=2.5,pointsize=8)
data(larain)
plot(larain,ylab='Inches',xlab='Year',type='o')
```
Exhibit 1.2 Scatterplot of LA Rainfall versus Last Year’s LA Rainfall
```{R}
# win.graph(width=3,height=3,pointsize=8)
plot(y=larain, x=zlag(larain),ylab='Inches', xlab='Previous Year Inches')
```
Exhibit 1.3 Time Series Plot of Color Property from a Chemical Process
```{R}
# win.graph(width=5, height=2.5, pointsize=8)
data(color)
plot(color,ylab='Color Property',xlab='Batch',type='o')
```
Exhibit 1.4 Scatterplot of Color Value versus Previous Color Value
```{R}
# win.graph(width=3,height=3,pointsize=8)
plot(y=color, x=zlag(color),ylab='Color Property',xlab='Previous Batch Color Property')
```
pratice running commands suggested in theory
```{R}
plot(color, color, ylab='Color Property',xlab='Batch',type='o')
as.vector(color)
plot(as.vector(color), color, ylab='Color Property',
xlab='Batch',type='o')
```
Exhibit 1.5 Abundance of Canadian Hare
```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
data(hare)
plot(hare,ylab='Abundance',xlab='Year',type='o')
```
Exhibit 1.6 Hare Abundance versus Previous Year’s Hare Abundance

```{R}
# win.graph(width=3, height=3,pointsize=8)
plot(y=hare,x=zlag(hare),ylab='Abundance',xlab='Previous Year Abundance')
```
### Monthly Average Temperatures in Dubuque, Iowa

Exhibit 1.7 Average Monthly Temperatures, Dubuque, Iowa
```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
data(tempdub)
plot(tempdub,ylab='Temperature',type='o')
```
### Monthly Oil Filter Sales

Exhibit 1.8 Monthly Oil Filter Sales
```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
data(oilfilters)
plot(oilfilters,type='o',ylab='Sales')
```

Exhibit 1.9 Monthly Oil Filter Sales with Special Plotting Symbols
```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
plot(oilfilters,type='l',ylab='Sales')
points(y=oilfilters,x=time(oilfilters),pch=as.vector(season(oilfilters)))
```

```{R}
y=rnorm(48)
plot(y, type='o', ylab='IID Normal Data')
```

## Chapter 2

```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
data(rwalk)
plot(rwalk,type='o',ylab='Random Walk')
```

Manually creating a random walk data
```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
n=60
set.seed(123)
sim.random.walk=ts(cumsum(rnorm(n)),freq=1,start=1)
plot(sim.random.walk,type='o',ylab='Another Random Walk')
```

### Chapter 3
Exhibit 3.1 Least Squares Regression Estimates for Linear Time Trend
```{R}
data(rwalk)
model1=lm(rwalk~time(rwalk))
summary(model1)
```
Exhibit 3.2 Random Walk with Linear Time Trend
```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
plot(rwalk,type='o',ylab='y')
abline(model1) # add the fitted least squares line from model1
```
pratice
```{R}
model1a=lm(rwalk~time(rwalk)+I(time(rwalk)^2))
summary(model1a)
```

```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
plot(rwalk,type='o',ylab='y')
abline(model1a)
```

Exhibit 3.3 Regression Results for the Seasonal Means Model
```{R}
data(tempdub)
month.=season(tempdub) # period added to improve table display
model2=lm(tempdub~month.-1) # -1 removes the intercept term
summary(model2)
```
pratice code
```{R}
sex=factor(c('M','F','M','M','F'))
sex
```

```{R}
sex=factor(c('M','F','M','M','F'),levels=c('M','F'))
sex
```

```{R}
table(sex)
```

```{R}
# fitted(model2)
# residuals(model2)
```
Exhibit 3.4 Results for Seasonal Means Model with an Intercept
```{R}
model3=lm(tempdub~month.)
summary(model3)
```

Exhibit 3.5 Cosine Trend Model for Temperature Series

```{R}
har.=harmonic(tempdub,1)
model4=lm(tempdub~har.)
summary(model4)
```
pratice
```{R}
M=matrix(1:6,ncol=2)
M
dim(M)
apply(M, 2, mean)
```

Exhibit 3.6 Cosine Trend for the Temperature Series
```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
plot(ts(fitted(model4),freq=12,start=c(1964,1)),ylab='Temperature',type='l', 
ylim=range(c(fitted(model4),tempdub))); points(tempdub)
# ylim ensures that the y axis range fits the raw data and thefitted values
```
Exhibit 3.8 Residuals versus Time for Temperature Seasonal Means
```{R}
# returns the (externally) Studentized residuals from the fitted mode
plot(y=rstudent(model3),x=as.vector(time(tempdub)),xlab='Time',ylab='Standardized Residuals',type='o')
```

```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
plot(y=rstudent(model3),x=as.vector(time(tempdub)),xlab='Time',ylab='Standardized Residuals',type='l')
points(y=rstudent(model3),x=as.vector(time(tempdub)),pch=as.vector(season(tempdub)))
```

```{R}
# returns the (internally) standardized residuals
plot(y=rstandard(model3),x=as.vector(time(tempdub)),xlab='Time',ylab='Standardized Residuals',type='o')
```
Exhibit 3.10 Standardized Residuals versus Fitted Values for the Temperature Seasonal Means Model
```{R}
plot(y=rstudent(model3),x=as.vector(fitted(model3)),xlab='Fitted Trend Values', ylab='Standardized Residuals',type='n')
points(y=rstudent(model3),x=as.vector(fitted(model3)),pch=as.vector(season(tempdub)))
```
Exhibit 3.11 Histogram of Standardized Residuals from Seasonal Means Model
```{R}
hist(rstudent(model3),xlab='Standardized Residuals', main='Histogram of the Standardized Residuals')
```

Exhibit 3.12 Q-Q Plot: Standardized Residuals of Seasonal Means Model
```{R}
qqnorm(rstudent(model3))
qqline(rstudent(model3))  # draws a line
```

Exhibit 3.13 Sample Autocorrelation of Residuals of Seasonal MeansModel
```{R}
acf(rstudent(model3)) # computes the sample autocorrelation function of the time series
```

```{R}
shapiro.test(rstudent(model3))
runs(rstudent(model3))
```

Exhibit 3.14 Residuals from Straight Line Fit of the Random Walk
```{R}
plot(y=rstudent(model1),x=as.vector(time(rwalk)),ylab='Standardized Residuals',xlab='Time',type='o')
```
Exhibit 3.15 Residuals versus Fitted Values from Straight Line Fit
```{R}
plot(y=rstudent(model1),x=fitted(model1),
ylab='Standardized Residuals',xlab='Fitted Trend Line Values',
type='p')
```
Exhibit 3.16 Sample Autocorrelation of Residuals from Straight Line Model
```{R}
acf(rstudent(model1))
```
Exhibit 3.17 Quantile-Quantile Plot of Los Angeles Annual Rainfall Series
```{R}
qqnorm(larain); qqline(larain)
```


# Question 2:

1.3 : Simulate a completely random process of length 48 with independent, normal values. Plot the time series plot. Does it look “random”? Repeat this exercise several
times with a new simulation each time.

```{R}
n=48
random_values=rnorm(n, mean = 0, sd = 1)
head(random_values)
```
```{R}
# win.graph(width=4.875, height=2.5,pointsize=8)
plot(ts(random_values), xlab = 'Time', ylab='value', type='o')
```

```{R}
num_simulations = 3
for (i in 1:num_simulations) {
    random_values=rnorm(n, mean = 0, sd = 1)
    # win.graph(width=4.875, height=2.5,pointsize=8)
    plot(ts(random_values), xlab = 'Time', ylab='value', type='o')
    grid()
}
```
**Observation** : After executing the script, I observed three time series plots, each illustrating a distinct simulation of the random process. The plots appear "random," displaying fluctuations without any noticeable trend or pattern. This behavior is typical of a stochastic process generated from a normal distribution. Each time I run the simulation, I see different plots because of the inherent randomness of the values.

-------------------------------------------------------------------------------------------------------

1.4: Simulate a completely random process of length 48 with independent, chi-square
distributed values, each with 2 degrees of freedom. Display the time series plot.
Does it look “random” and nonnormal? Repeat this exercise several times with a
new simulation each time.

```{R}
chi_sqr_value = rchisq(n, df = 2)
# win.graph(width=4.875, height=2.5,pointsize=8)
plot(chi_sqr_value,type = 'o')
```

```{R}
num = 3
for (i in 1:num)
{
    chi_sqr_value = rchisq(n, df = 2)
    # win.graph(width=4.875, height=2.5,pointsize=8)
    plot(chi_sqr_value,type = 'o')
    grid()
}
```

**Observation**: After executing the script, I observed three time series plots, each depicting a distinct simulation of the random process. The plots appear "random," displaying fluctuations; however, they do not conform to a normal distribution shape. Values drawn from a chi-square distribution, particularly with 2 degrees of freedom, typically exhibit positive skewness. Each time I run the simulation, I encounter different plots because of the inherent randomness of the values.

-------------------------------------------------------------------------------------------------------

1.5 : Simulate a completely random process of length 48 with independent, t-distributed values each with 5 degrees of freedom. Construct the time series plot. Does it
look “random” and nonnormal? Repeat this exercise several times with a new
simulation each time

```{R}
n = 48
t_dis_value =  rt(n, df = 5)
plot(t_dis_value, type = 'o', ylab='value')
```
simulation

```{R}
nums = 3
for (i in 1:nums)
{
    t_dis_value =  rt(n, df = 5)
    plot(t_dis_value, type = 'o', ylab='value')
}
```

**Observation** : After executing the script, I observed three time series plots, each illustrating a different simulation of the random process. The plots appear "random," displaying fluctuations. However, since the values are drawn from a t-distribution with 5 degrees of freedom, they may exhibit heavier tails compared to a normal distribution, resulting in a nonnormal appearance. Each time I run the simulation, I see different plots due to the inherent randomness of the values.







